import {
  AlertTriangle,
  AlignLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Bell,
  BookOpen,
  Bot,
  Brain,
  Building2,
  Check,
  CheckCircle,
  ChevronLeft,
  Circle,
  CircleDot,
  Clock,
  Code2,
  FileText,
  Flame,
  GraduationCap,
  Hammer,
  HardDrive,
  Lightbulb,
  Link as LinkIcon,
  Loader2,
  Maximize,
  Menu,
  Minimize,
  Megaphone,
  MessageCircle,
  Mic2,
  Paperclip,
  Pause,
  PenLine,
  Play,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Settings,
  Sparkles,
  Square,
  Target,
  Trash2,
  Trophy,
  UploadCloud,
  User,
  Video,
  Volume2,
  VolumeX,
  Wrench,
  X,
  XCircle,
  Lock,
  Unlock,
} from 'lucide-react';

const ICONS = {
  alert: AlertTriangle,
  alignLeft: AlignLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  badgeCheck: BadgeCheck,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  brain: Brain,
  building: Building2,
  check: Check,
  checkCircle: CheckCircle,
  chevronLeft: ChevronLeft,
  circle: Circle,
  circleDot: CircleDot,
  clock: Clock,
  code: Code2,
  file: FileText,
  flame: Flame,
  graduation: GraduationCap,
  hammer: Hammer,
  hardDrive: HardDrive,
  lightbulb: Lightbulb,
  link: LinkIcon,
  loader: Loader2,
  maximize: Maximize,
  menu: Menu,
  minimize: Minimize,
  megaphone: Megaphone,
  message: MessageCircle,
  mic: Mic2,
  paperclip: Paperclip,
  pause: Pause,
  pen: PenLine,
  play: Play,
  refresh: RefreshCw,
  rocket: Rocket,
  search: Search,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  square: Square,
  target: Target,
  trash: Trash2,
  trophy: Trophy,
  upload: UploadCloud,
  user: User,
  video: Video,
  volume: Volume2,
  volumeX: VolumeX,
  wrench: Wrench,
  x: X,
  xCircle: XCircle,
  lock: Lock,
  unlock: Unlock,
};

export default function AppIcon({ name, size = 16, strokeWidth = 2, className = '' }) {
  const Icon = ICONS[name] || Circle;
  return (
    <Icon
      aria-hidden="true"
      className={`inline-block shrink-0 align-[-0.16em] ${className}`}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}
